/**
 * @file
 */

'use strict';

var generators = require('yeoman-generator');

module.exports = generators.Base.extend({

  constructor: function () {
    generators.Base.apply(this, arguments);
  },

  prompting: function () {
    this.log('Prompting.');

    var asyncWait = this.async();

    var questions = [{
      name: 'profileName',
      message: 'Profile full name'
    }, {
      name: 'machineName',
      message: 'Machine name'
    }, {
      name: 'profileDescription',
      message: 'Description',
      default: 'Auto-generated by "yo drupal-profile"'
    }, {
      type: 'list',
      name: 'drupalCore',
      message: 'Drupal core version',
      choices: ['Drupal 6', 'Drupal 7', 'Drupal 8'],
      default: 'Drupal 7'
    }, {
      type: 'confirm',
      name: 'inheritBasicProfile',
      message: 'Inherit from "Basic profile"',
      default: false
    }, {
      name: 'adminTheme',
      message: 'Admin theme',
      default: 'adminimal_theme'
    }, {
      type: 'checkbox',
      name: 'modules',
      message: 'Modules',
      choices: ['devel', 'views', 'ctools', 'entity', 'admin_menu']
    }];

    this.prompt(questions, function ( answers ) {
      this.profileName = answers.profileName;
      this.machineName = answers.machineName;
      this.profileDescription = answers.profileDescription;
      this.drupalCore = answers.drupalCore;
      this.inheritBasicProfile = answers.inheritBasicProfile;
      this.adminTheme = answers.adminTheme;
      this.modules = answers.modules;

      asyncWait();
    }.bind(this));
  },

  generateFolder: function () {
    this.log('Folder generation.');
    this.mkdir(this.machineName);
  },

  generateInfoFile: function() {
    this.log('Add info file');
    this.template(this.drupalCore + '/standard/standard.info', this.machineName + '/' + this.machineName + '.info');
  },

  generateProfileFile: function () {
    this.log('Add profile file');
    this.template(this.drupalCore + '/standard/standard.profile', this.machineName + '/' + this.machineName + '.profile');
  },

  generateInstallFile: function () {
    this.log('Add install file');
    this.template(this.drupalCore + '/standard/standard.install', this.machineName + '/' + this.machineName + '.install');
  }

});
